### ISSUE TITLE
failed to downlaod

### ISSUE THREAD

**Issue by d7eeem** [arelate/vangogh#143]
ERROR no filename for manual-url [/downloads/warhammer_40000_space_marine/92102

 i have my library linked to my "https://github.com/Sude-/lgogdownloader" downloaded files but Vangogh is not recognizing the structure files are downloaded like this 

/mnt/deimos/games/romm/Library/roms/pc-gog/downloadswarhammer_40000_dawn_of_war_dark_crusade
/mnt/deimos/games/romm/Library/roms/pc-gog/downloadswarhammer_40000_dawn_of_war_soulstorm
/mnt/deimos/games/romm/Library/roms/pc-gog/downloadswarhammer_40000_dawn_of_war_winter_assault
/mnt/deimos/games/romm/Library/roms/pc-gog/downloadswarhammer_40000_gladius_relics_of_war

running via dockage 
```yaml
services:
  vangogh:
    container_name: vangogh
    image: ghcr.io/arelate/vangogh:latest
    environment:
      # Configuration
      - VANGOGH_OS=Windows,Linux 
      - VANGOGH_LANG-CODE=en
      - VANGOGH_NO-PATCHES=true
      # - VANGOGH_SYNC_DEBUG=true 
      # - VANGOGH_DOWNLOADS-LAYOUT=sharded
      # Web UI credentials
      - VANGOGH_SERVE_ADMIN-USERNAME=admin-user
      - VANGOGH_SERVE_ADMIN-PASSWORD=admin-password
      - VANGOGH_SERVE_SHARED-USERNAME=shared-user
      - VANGOGH_SERVE_SHARED-PASSWORD=shared-password
    volumes:
      # Downloads & cold storage
      - /mnt/deimos/games/romm/Library/roms/pc-gog/downloads:/var/lib/vangogh/downloads
      - /mnt/deimos/games/romm/Library/roms/pc-gog/backups:/var/lib/vangogh/backups
      - /mnt/deimos/games/romm/Library/roms/pc-gog/logs:/var/lib/vangogh/logs
      - /mnt/deimos/games/romm/Library/roms/pc-gog/recycle_bin:/var/lib/vangogh/recycle_bin
      # Hot storage
      - /mnt/deimos/appdata/vangogh/input:/var/lib/vangogh/input
      - /mnt/deimos/appdata/vangogh/vangogh:/var/lib/vangogh/output
      - /mnt/deimos/appdata/vangogh/checksums:/var/lib/vangogh/checksums
      - /mnt/deimos/appdata/vangogh/images:/var/lib/vangogh/images
      - /mnt/deimos/appdata/vangogh/description_images:/var/lib/vangogh/description_images
      - /mnt/deimos/appdata/vangogh/metadata:/var/lib/vangogh/metadata
     
     # Host 
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    ports:
      - 1853:1853
networks: {}
````
